import { GlobalThemeProvider } from '@/components/global-theme-provider'
import { NextAuthSessionProvider } from '@/components/next-auth-session-provider'
import { ReactQueryProvider } from '@/components/react-query-provider'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <GlobalThemeProvider>
          <NextAuthSessionProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </NextAuthSessionProvider>
        </GlobalThemeProvider>
      </body>
    </html>
  )
}
